### ISSUE TITLE
Limitations on up to 10,000 UploadParts

### ISSUE THREAD

**Issue by liuao-hash** [hawkey999/multipart-upload-s3-python#1]
I have a single file of 400G, and I want to upload it to S3 through a breakpoint in your script, but I found a limit in uploadscript 10000 in your script. Can you change this limit, and if so, what should I do? What about operation?   thank you

**Comment by huangzbaws** [comment]
There is a limitation for AWS S3 multi-part upload API, so we can do nothing from client side. But since your file is 400G, please change the ChunkSize in config file to 50MB. That can help your job doing well.

ChunkSize = 50 * Megabytes

BTW, the tool has been upgraded to version 1.0.
